globalconfig:
  oscr_ip: 0.0.0.0
  inputport_ui: 4455 # inputport for UI-Clients, blocks inputport_data for short time
  inputport_data: 4007 # inputport for automation-data clients
  inputport_settings: 4999 # global configs can be changed with this port
  number_sources: 64
  max_gain: 2 # max gain for the audiorouter
  min_dist: 0.001
  number_direct_sends: 46 # including subwoofer
  send_changes_only: 1 # checks every input for changes, if set to 1 might be slower
  data_port_timeout: 2 # time a change in the ui-port blocks incoming automation, set to 0 to deactivate this feature
  render_units: ["ambi", "wfs", "reverb"]
# changed to remove sendport, rename listenport to port
receivers:
  - type: audiorouter
    hosts:
      - hostname: 127.0.0.1
        port: 57120
      - hostname: 127.0.0.1
        port: 57119
    updateintervall: 5

  - type: audiorouterWFS
    hosts:
      - hostname: 127.0.0.1
        port: 57121
    updateintervall: 5

  - type: audiomatrix
    hosts:
      - hostname: 127.0.0.1
        port: 57122
    paths:
      - path: /source/gain/wfs
        renderer: wfs
        type: gain
      - path: /source/gain/ambi
        type: gain
        renderer: ambi
      - path: /source/pos
        type: position
        format: aed
      - path: /source/xyz
        type: pos
        format: xyz

    updateintervall: 5

  - type: wonder
    hosts:
      - hostname: 127.0.0.1
        port: 58100
    updateintervall: 50

  - type: scengine
    hostname: 127.0.0.1
    port: 57120
    updateintervall: 10
    dataformat: aedrad
